# This file was generated by GoReleaser. DO NOT EDIT.
class Dockle < Formula
  desc ""
  homepage "https://github.com/goodwithtech/dockle"
  url "https://github.com/goodwithtech/dockle/releases/download/v0.0.17/dockle_0.0.17_macOS-64bit.tar.gz"
  version "0.0.17"
  sha256 "9a848b352d73c1ec9ea3b6a9c18a780e178eba4cdeac5c28f4cf8ab0404cfce3"

  def install
    bin.install "dockle"
  end

  test do
    system "#{bin}/program --version"
  end
end
