# This file was generated by GoReleaser. DO NOT EDIT.
class Dockle < Formula
  desc ""
  homepage "https://github.com/goodwithtech/dockle"
  url "https://github.com/goodwithtech/dockle/releases/download/v0.1.1/dockle_0.1.1_macOS-64bit.tar.gz"
  version "0.1.1"
  sha256 "c15b54927c855da516e20dbfb2646dbbfff6bfabab85af4babdd0a1ffe1e8ca4"

  def install
    bin.install "dockle"
  end

  test do
    system "#{bin}/program --version"
  end
end
