# This file was generated by GoReleaser. DO NOT EDIT.
class Dockle < Formula
  desc ""
  homepage "https://github.com/goodwithtech/dockle"
  url "https://github.com/goodwithtech/dockle/releases/download/v0.0.18/dockle_0.0.18_macOS-64bit.tar.gz"
  version "0.0.18"
  sha256 "7ab559921ff7a2b91e099cf53e293c474495bfb49ca7b219516141d41e44480d"

  def install
    bin.install "dockle"
  end

  test do
    system "#{bin}/program --version"
  end
end
