# This file was generated by GoReleaser. DO NOT EDIT.
class Dockle < Formula
  desc "Simple security auditing, helping build the Best Docker Images"
  homepage "https://github.com/goodwithtech/dockle"
  version "0.1.11"

  if OS.mac?
    url "https://github.com/goodwithtech/dockle/releases/download/v0.1.11/dockle_0.1.11_macOS-64bit.tar.gz"
    sha256 "4244d59a42d020ae0190a5f1ce49eb526e9b855c61a2b855d6ae1100de2dfcbe"
  elsif OS.linux?
    url "https://github.com/goodwithtech/dockle/releases/download/v0.1.11/dockle_0.1.11_Linux-64bit.tar.gz"
    sha256 "dbbb6f47b91b4ed6603c30b1354391f0ed0620ea209cf4e7a7880a116b0fb24b"
  end

  def install
    bin.install "dockle"
  end

  test do
    system "#{bin}/program --version"
  end
end
